[tool.isort]
profile = "black"
src_paths = ["isort", "test"]


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
version_files = [
    "__init__.py",
    "pyproject.toml:version"
]
annotated_tag = true
tag_format = "v$major.$minor.$patch$prerelease"
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]
